db_file: bot.db

messages:
  responses:
    Start: "ะัะธะฒะตั, ั ะะฑะตัะฐะปะบะธะฝ ะัะพะฒะตัััะตะปั.\nะัะปะธ ะทะฐะบะปััะฐะตัั ัะพ ะผะฝะพะน ะบะพะฝััะฐะบั ะพะฑะตัะฐะฝะธะต ะดะพะปะถะฝะพ ะฑััั ะฒัะฟะพะปะฝะตะฝะพ ะฒ ััะพะบ ะธะปะธ ัะตะฑะต ะฑัะดะตั ะพัะตะฝั ัััะดะฝะพ!\nะะปั ัะพะณะพ ััะพะฑั ะฟะพะพะฑะตัะฐัั ััะพ-ัะพ ะฒะฒะตะดะธ ะบะพะผะฐะฝะดั:\n/promise 'ะพะฑะตัะฐะฝะธะต' #ะดะพ 'ะดะฐัะฐ'.\nะัะธะผะตั: /promise ะะฐะนะดั ัะฐะฑะพัั #ะดะพ 13.02.2023\nะงัะพะฑั ัะฒะธะดะตัั ัะฟะธัะพะบ ัะฒะพะธั ะพะฑะตัะฐะฝะธะน ะฒะฒะตะดะธ ะบะพะผะฐะฝะดั: /mypromises\nะฃะดะฐะปะธัั ะพะฑะตัะฐะฝะธะต ะธะท ะฒัะฟะพะปะฝะตะฝะฝัั: /delete"
    Commit: "ะฏ ะทะฐะฟะพะผะฝะธะป ะพะฑะตัะฐะฝะธะต. ะัะตะผั ะฟะพัะปะพ.."
    Unknown: "ัะท ัะพ ะทะฐ ะบะพะผะฐะฝะดะฐ"
    NoCommits: "ะฃ ัะตะฑั ะฟะพะบะฐ ะฝะตั ะฝะธ ะพะดะฝะพะณะพ ะฐะบััะฐะปัะฝะพะณะพ ะพะฑะตัะฐะฝะธั, ะฝะพ ัั ะผะพะถะตัั ะธัะฟัะฐะฒะธัั ััะพ ะฟััะผะพ ัะตะนัะฐั."
    Nonsense: " ััะพ? ะฎะทะฐะน ะบะพะผะฐะฝะดั /start ััะพะฑั ะฟะพะฝััั ะบะฐะบ ั ัะฐะฑะพัะฐั."
    Ok1: "ะัะต ะธะดะตั ะฟะพ ะฟะปะฐะฝั"
    Ok2: "ะัะต ะััะตะผ!"
    Ok3: "ะะฐะฑะพัะฐั"
    Ok4: "ะะบะตั"
    Done: "ะัะต ัะถะต ะณะพัะพะฒะพ"
    KeepWorking: "Keep Working"
    Congrats: "๐ฅณะััะบะฐ. ะะตัะตะผะตัะฐั ะฒ ะทะฐะบะพะฝัะตะฝะฝัะต.๐ฅณ"
    TooManyCommits: "ะกะปะธัะบะพะผ ะผะฝะพะณะพ ัะตะบััะธั ะพะฑะตัะฐะฝะธะน. ะกะฝะฐัะฐะปะฐ ััะพ-ัะพ ะดะพะดะตะปะฐะน - ัะพะณะดะฐ ะผะพะถะฝะพ ะฑัะดะตั ะฟะพะพะฑะตัะฐัั ััะพ-ัะพ ะฝะพะฒะพะต."
    NoDoneCommits: " ะฃ ัะตะฑั ะฟะพะบะฐ ะฝะตั ะฒัะฟะพะปะฝะตะฝะฝัั ะพะฑะตัะฐะฝะธะน."
    DeleteHeader: "ะฃะดะฐะปััั ะผะพะถะฝะพ ัะพะปัะบะพ ัะถะต ะฒัะฟะพะปะฝะตะฝะฝัะต ะพะฑะตัะฐะฝะธั.\n"
    CommitIsDeleted: "ะะฑะตัะฐะฝะธะต ะฒัะฟะธะปะตะฝะพ ะธะท ัะฟะธัะบะฐ ะทะฐะบะพะฝัะตะฝะฝัั."
    Initiate: "ะฅะพัะพัะธะน ะฟะพะฒะพะด ะทะฐัะธะบัะธัะพะฒะฐัั ะฝะฐะผะตัะตะฝะธะต ;3\nะฏ ะผะพะณั ะฟัะพัะปะตะดะธัั ะทะฐ ะฒัะฟะพะปะฝะตะฝะธะตะผ ะธ ะฝะฐะฟะพะผะธะฝะฐัั ะพ ะดะตะดะปะฐะนะฝะฐั. ะะพะผะฐะฝะดะฐ /start ะฟะพะผะพะถะตั ัะฐะทะพะฑัะฐัััั."
  errors:
    default: "ะะตะธะทะฒะตััะฝะฐั ะพัะธะฑะบะฐ"
    noCommit: "ะขะพ ะปะธ ั ััะฟะพะน, ัะพ ะปะธ ะพะฑะตัะฐะฝะธะต ะบัะธะฒะพะต.\nะะปั ัะพะณะพ ััะพะฑั ะฟะพะพะฑะตัะฐัั ััะพ-ัะพ ะฒะฒะตะดะธ ะบะพะผะฐะฝะดั:/promise 'ะพะฑะตัะฐะฝะธะต' #ะดะพ 'ะดะฐัะฐ'.\nะัะธะผะตั: /promise ะะฐะนะดั ัะฐะฑะพัั #ะดะพ 13.02.2023"
    noDate: "ะัะธะฒะฐั ะดะฐัะฐ."
    badYear: "ะัะธะฒะพ ัะบะฐะทะฐะฝ ะณะพะด."
    badMonth: "ะัะธะฒะพ ัะบะฐะทะฐะฝ ะผะตััั"
    badDay: "ะะตะฝั ัะบะฐะทะฐะฝ ะบัะธะฒะพ"
    existingCommit: "ะญัะพ ะพะฑะตัะฐะฝะธะต ั ัะตะฑั ัะถะต ะฑัะปะพ. ะงะตะบะฝััั ะผะพะถะฝะพ ะบะพะผะฐะฝะดะพะน /mypromises"
    jsonError: "ะัะพะฑะปะตะผั ั ะทะฐะฟะฐะบะพะฒะบะพะน/ัะฐัะฟะฐะบะพะฒะบะพะน JSON"
    tooSoon: "ะะตะดะปะฐะนะฝ ะดะพะปะถะตะฝ ะฑััั ะผะธะฝะธะผัะผ ะทะฐะฒััะฐ"
    tooLongError: "ะะปะธะฝะฐ ะพะฑะตัะฐะฝะธั ะฝะต ะดะพะปะถะฝะฐ ะฑััั ะฑะพะปััะต 150 ัะธะผะฒะพะปะพะฒ"
  scales:
    start: "๐ข๐ข๐ข๐ข๐ข๐ข๐ข๐ข๐ข๐ข"
    ten: "๐คญ๐ข๐ข๐ข๐ข๐ข๐ข๐ข๐ข๐ข"
    twenty: "๐๐๐ข๐ข๐ข๐ข๐ข๐ข๐ข๐ข"
    thirty: "๐ณ๐ณ๐ณ๐ก๐ก๐ก๐ก๐ก๐ก๐ก"
    forty: "๐ซฅ๐ซฅ๐ซฅ๐ซฅ๐ก๐ก๐ก๐ก๐ก๐ก"
    fifty: "๐ถโ๐ซ๏ธ๐ถโ๐ซ๏ธ๐ถโ๐ซ๏ธ๐ถโ๐ซ๏ธ๐ถโ๐ซ๏ธ๐๐๐๐๐"
    sixty: "๐คข๐คข๐คข๐คข๐คข๐คข๐๐๐๐"
    seventy: "๐๐๐๐๐๐๐๐ด๐ด๐ด"
    eighty: "๐งป๐งป๐งป๐งป๐งป๐งป๐งป๐งป๐ด๐ด"
    ninety: "๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐ฅต"
    ninetyFive: "๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐ฉ๐งป"
    end: "โ๏ธโ๏ธโ๏ธโ๏ธโ๏ธโ๏ธโ๏ธโ๏ธโ๏ธโ๏ธ"
  parts:
    hundredth: "ะะพั ะธ ะบะฐะฟะฝัะป 1% ะพั ะทะฐะปะพะถะตะฝะฝะพะณะพ ะฒัะตะผะตะฝะธ. ะะฐะทะฐะปะพัั ะฑั - ะฒัะตะณะพ ะพะดะธะฝ ะฟัะพัะตะฝั. ะญัะพ ะฒะตะดั ะบะฐะบ ะพะดะฝะฐ ะฟะฐะปะพัะบะฐ ะธะท ัะฟะฐะบะพะฒะบะธ ั ะบะฐััะพัะบะพะน ััะธ! ะะดะฝะฐะบะพ ะตัะปะธ ะฝะฐะฟัะธะผะตั ะบัะพ-ัะพ ะทะฐะฑัะดะตั ะฟัะพ ะดะตะดะปะฐะนะฝ ะธ ะบ ะฝะตะผั ะฟัะธะดัั ะบะพะปะปะตะบัะพัั, ะบะพัะพััะต ะทะฐัะพััั ััะพ-ัะพ ะพัะฟะธะปะธัั ะฝะฐ 1%, ะฒัััะฝะธััั ััะพ ัะตะปะธะบ ะฒ ะปัััะตะผ ัะปััะฐะต ะพัะดะตะปะฐะตััั ะบะธัััั..ะัะปะธัะฝัะน ะฟะพะฒะพะด ะทะฐะดัะผะฐัััั ะพะฑ ะพัะฒะตัััะฒะตะฝะฝะพััะธ!๐ช๐ช๐ช"
    tenth: "ะะตัะฒัะต 10% ะดะพ ะดะตะดะปะฐะนะฝะฐ ะฟัะพะนะดะตะฝั. ะะฐะบ ััะฟะตัะธ?โบ๏ธ"
    fifth: "ะะดะฝะฐ ะฟััะฐั ะพั ะทะฐะปะพะถะตะฝะฝะพะณะพ ะฝะฐ ัะตะปั ะฒัะตะผะตะฝะธ ะฒััะปะฐ. ะญัะพ ัะถะต ะบะฐะบ ะฟะฐะปะตั ะพะดะฝะพะน ััะบะธ๐ช"
    third: "ะขัะตัั ััะพะบะฐ ะทะฐ ัะฟะธะฝะพะน. ะะตัะถะธะผ ะทะฐ ัะตะฑั ะบัะปะฐะบะธ ะธ ะฑะธัั๐"
    half: "ะะพั ะธ ัะบะฒะฐัะพั. ะะฟะตัะตะดะธ ัะพะฒะฝะพ ััะพะปัะบะพ ะถะต ะฒัะตะผะตะฝะธ ัะบะพะปัะบะพ ะฟัะพัะปะพ. ะะฐะบ ััะฟะตัะธ?๐ง"
    sixtySix: "2/3 ััะพะบะฐ ะผะธะฝัะปะพ. ะะฐะดะตััั ั ัะตะฑั ะตััั ะฟะปะฐะฝ ะธ ัั ะตะณะพ ะฟัะธะดะตัะถะธะฒะฐะตัััั๐งป"
    sixtyNine: "ะฃะถ ัะบะพัะพ 70% ะพั ััะพะบะฐ ะฒัะนะดะตั, ะฐ ะฟะพะบะฐ ััะพ ัะพะปัะบะพ 69. ะขะตะผ ะฝะต ะผะตะฝะตะต ะฝะต ะฒัะตะผั ัะฐััะปะฐะฑะปััััั..๐ฅต"
    eighty: "80% ะฒัะตะผะตะฝะธ ะบะฐะฟะฝัะปะพ. ะะฐัะธะฝะฐะตั ััะพ-ัะพ ะฟะพะดะณะพัะฐัั๐น"
    ninety: "ะั ะฒัะตะณะพ ััะพะบะฐ ะพััะฐะปะพัั 10%. ะะะข ะะะะะะะ ะะ ะะะกะะะงะะฃ!๐บ๐บ๐บ"
    ninetyFive: "ะะพัะปะตะดะฝะธะต 5% ะดะพ ะดะตะดะปะฐะนะฝะฐ. ะั ััั ะฒัะฑัะฐะปะธัั ะฒ ะปะตั ะฟะพัััะตะปััั ะธ ะฒัะฟะพะผะฝะธะปะธ ะพ ัะตะฑะต๐ซ"
    end: "ะขะะะ ะะะะะฏ ะะซะจะะ. ะะพัะปะตะดะฝะธะน ัะฐะฝั ะธะปะธ ะพะฑะตัะฐะฝะธะต ะพัะฟัะฐะฒะปัะตััั ะฒ 'ะัะพัะพัะฐะฝะฝัะต'"